### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by MikhailY** [X1machinemaker1X/HeadDrops#2]
paperspigot 1.12.2
headdrops 2.1.4

[08:46:04] [Server thread/ERROR]: Could not pass event BlockBreakEvent to HeadDrops v2.1.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:889) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at me.x1machinemaker1x.headdrops.EventListener.onBlockBreak(EventListener.java:56) ~[HeadDrops.jar:?]
	at sun.reflect.GeneratedMethodAccessor440.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit3.jar:git-Spigot-2086bb0-21d5f75]
	... 17 more

**Comment by Machine-Maker** [comment]
Ok, this should be fixed in v2.1.5
