### ISSUE TITLE
Craft Scheduler Thread - 3/WARN

### ISSUE THREAD

**Issue by Blueeyestar** [X1machinemaker1X/HeadDrops#3]
[18:19:37] [Craft Scheduler Thread - 3/WARN]: [HeadDrops] Plugin HeadDrops v2.0 generated an exception while executing task 6
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at de.timolia.headdrops.Metrics.postPlugin(Metrics.java:357) ~[?:?]
	at de.timolia.headdrops.Metrics.access$400(Metrics.java:57) ~[?:?]
	at de.timolia.headdrops.Metrics$1.run(Metrics.java:234) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot-latest.jar:git-Paper-1248]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [PaperSpigot-latest.jar:git-Paper-1248]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [PaperSpigot-latest.jar:git-Paper-1248]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]

**Comment by Machine-Maker** [comment]
Hmm, ok. looks like you are using an older version of HeadDrops v2.0. Please download the latest version.
